### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by LY978757** [zhangrengang/phytop#7]
python version = Python 3.8.8
path = phytop/example_data
command line : phytop astral.tree

24-12-06 02:26:46 [INFO] No DRMAA (see https://github.com/pygridtools/drmaa-python), Switching to local mode.
24-12-06 02:26:47 [INFO] Command: /home/qyliu/miniconda3/envs/phytop/bin/phytop astral.tree
24-12-06 02:26:47 [INFO] Version: 0.3
24-12-06 02:26:47 [INFO] Arguments: {'astral': 'astral.tree', 'alter': None, 'genetrees': None, 'align': False, 'cp': False, 'branch_size': 48, 'leaf_size': 60, 'sort': False, 'notext': False, 'figsize': 3, 'fontsize': 13, 'figfmt': 'png', 'colors': None, 'polytomy_test': False, 'pie': False, 'pie_size': 30, 'add_bl': False, 'test_clades': None, 'astral_bin': 'astral-pro', 'outgroup': None, 'clades': None, 'collapsed': None, 'onshow': None, 'noshow': None, 'subset': None, 'prefix': None, 'tmpdir': 'tmp'}
24-12-06 02:26:47 [INFO] Clades info file: `tmp/astral.tree.nodes.tsv`, which can be renamed and edited as input of `-clades`
0.16233895294120287 0.0 0 6476.276988 5586.541891 2337.777784 14400.596662999998 [0.44972282326604873, 0.38793822379274845, 0.16233895294120287]
[0, 1, 2] [0.44972282326604873, 0.38793822379274845, 0.16233895294120287] 0.16233895294120287
tmp/astral.tree.N3.bar.png
0.007160617609422493 0.16802899201569788 1 16289.58301 128.942346 107.734103 16526.259459 [0.985678764781155, 0.007802270460529382, 0.00651896475831555]
[0, 1, 2] [0.985678764781155, 0.007802270460529382, 0.00651896475831555] 0.007160617609422493
tmp/astral.tree.N4.bar.png
24-12-06 02:26:48 [INFO] Labeled tree file: `tmp/astral.tree.label.tree`
24-12-06 02:26:48 [INFO] Information file: `astral.tree.info.tsv`
24-12-06 02:26:48 [INFO] Final plot: `astral.tree.pdf`
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

"I used the above commands, but I encountered this error. How can I resolve it?"

**Comment by NZY1314** [comment]
Hi LY978757,

 I also met the same error. Have you ever resolved it?

Best,
Zhengyang Niu

**Comment by shang-hongyun** [comment]
Hi，you can try to run in linux：
export QT_QPA_PLATFORM='offscreen'

**Comment by shang-hongyun** [comment]
> Hi LY978757,
> 
> I also met the same error. Have you ever resolved it?
> 
> Best, Zhengyang Niu

Hi，you can try to run in linux：
export QT_QPA_PLATFORM='offscreen'

**Comment by NZY1314** [comment]
Hi Hongyun,

It works. Thanks a lot!

Best,
Zhengyang

**Comment by LY978757** [comment]
> > Hi LY978757,
> > I also met the same error. Have you ever resolved it?
> > Best, Zhengyang Niu
> 
> Hi，you can try to run in linux： export QT_QPA_PLATFORM='offscreen'

run sucessfully,thanks
